package vn.ai.faceauth.sdk.domain.model.exceptions;

import kotlin.Metadata;

@Metadata(d1 = {"\u0000\f\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0002\b\u000b\b\u0080\u0001\u0018\u00002\b\u0012\u0004\u0012\u00020\u00000\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003j\u0002\b\u0004j\u0002\b\u0005j\u0002\b\u0006j\u0002\b\u0007j\u0002\b\bj\u0002\b\tj\u0002\b\nj\u0002\b\u000b¨\u0006\f"}, d2 = {"Lvn/ai/faceauth/sdk/domain/model/exceptions/ErrorsTypes;", "", "<init>", "(Ljava/lang/String;I)V", "CONTEXT_SWITCHED", "EMULATOR", "MAX_RETRY", "NETWORK_ERROR", "PERMISSION_DENIED", "PERMISSION_UNKNOWN", "TIME_OUT", "USER_CANCELED", "authenSDK_release"}, k = 1, mv = {1, 6, 0})
/* loaded from: classes4.dex */
public enum ErrorsTypes {
    CONTEXT_SWITCHED,
    USER_CANCELED,
    PERMISSION_DENIED,
    PERMISSION_UNKNOWN,
    MAX_RETRY,
    TIME_OUT,
    EMULATOR,
    NETWORK_ERROR
}
